### ISSUE TITLE
 ERROR: The template "theme::content" could not be found at "templates/content.php".  

### ISSUE THREAD

**Issue by hariprasadraja** [dauxio/daux.io#156] opened 2019-11-01 16:31 UTC
**Describe the bug**
I have got the below error while running through the docker. please help me to resolve this

```
docker run --rm -it -w /build -v "$PWD":/build daux/daux.io daux -vvv generate --source=./Notebooks --destination=./Notebook-site
Copying Static assets ...
[  OK  ]
Generating ...
- AWS_Udmey/Title.html
Using cache dir '/tmp/dauxio/'
Not found in the cache, generating...
Running conversion
Starting Template engine with basedir 'templates' and theme folder 'templates'.
Rendering template 'theme::content'
[ FAIL ]

In Template.php line 144:
                                                                                
  [LogicException]                                                              
  The template "theme::content" could not be found at "templates/content.php".  
                                                                                

Exception trace:
  at /daux/vendor/league/plates/src/Template/Template.php:144
 League\Plates\Template\Template->render() at /daux/vendor/league/plates/src/Engine.php:277
 League\Plates\Engine->render() at /daux/libs/Format/HTML/Template.php:75
 Todaymade\Daux\Format\HTML\Template->render() at /daux/libs/Format/HTML/ContentPage.php:116
 Todaymade\Daux\Format\HTML\ContentPage->generatePage() at /daux/libs/Format/Base/SimplePage.php:20
 Todaymade\Daux\Format\Base\SimplePage->getContent() at /daux/libs/Format/HTML/Generator.php:184
 Todaymade\Daux\Format\HTML\Generator->Todaymade\Daux\Format\HTML\{closure}() at /daux/libs/Console/RunAction.php:25
 Todaymade\Daux\Format\HTML\Generator->runAction() at /daux/libs/Format/HTML/Generator.php:193
 Todaymade\Daux\Format\HTML\Generator->generateRecursive() at /daux/libs/Format/HTML/Generator.php:166
 Todaymade\Daux\Format\HTML\Generator->generateRecursive() at /daux/libs/Format/HTML/Generator.php:73
 Todaymade\Daux\Format\HTML\Generator->generateAll() at /daux/libs/Console/Generate.php:56
 Todaymade\Daux\Console\Generate->execute() at /daux/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /daux/vendor/symfony/console/Application.php:934
 Symfony\Component\Console\Application->doRunCommand() at /daux/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /daux/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /daux/bin/daux:71

generate [-c|--configuration CONFIGURATION] [--value VALUE] [-s|--source SOURCE] [-p|--processor PROCESSOR] [--no-cache] [-t|--themes THEMES] [-f|--format FORMAT] [--delete] [-d|--destination DESTINATION] [--search]
```

**Comment by onigoetz** [comment] 2019-11-15 13:39
Hello,
I ran the same command as you locally with the latest version of the docker image and couldn't reproduce this issue.

Can you please : 
1. run `docker pull daux/daux.io` and re-run the command to be sure you have the latest version ?
2. give me the content of your `Notebooks/config.json` so I can check if you have custom options ?

In my version I see a difference to what you have : 

```
Your version:
Starting Template engine with basedir 'templates' and theme folder 'templates'.

My version:
Starting Template engine with basedir '/daux/libs/Format/HTML/../../../templates' and theme folder '/daux/libs/Format/HTML/../../../templates'.
```

Maybe it's fixed in the latest version?

**Comment by hariprasadraja** [comment] 2019-11-15 17:58
It is working, but not in a way as we think. 

1.  I ran the command `docker pull daux/daux.io` 
2. I don't have config.json 

**What did I find?** 
 I have a folder named `Templates\`, where I have stored my file templates.  I have just deleted that folder and ran that command. Now the document is getting generated. 

I don't know how that folder is associated with the issue (or) why it is treating some other path instead of the actual one which you have mentioned. 

It just occurred to me either can this issue happened because of that `Templates/` directory. 
Thus, I have deleted it and It's working. 

my directory will look like this,  
```
- Notebook  
  - AWS Udmey
       - File1.md
   - Templates 
      - File1.md
      - File2.md
```

**Comment by onigoetz** [comment] 2019-11-15 19:42
oh I get it, this looks like a bug. I'll have a look.

**Comment by int2k** [comment] 2019-12-20 19:19
My current solution for this is adding templates key in my doc config.json file
```json
{
  "templates": "<set-to-daux-template-directory>"
}
```

**Closed** 2020-11-02 20:42 UTC
Labels: bug

**Comment by Bockiii** [comment] 2022-07-09 18:29
For anyone stumbling over this issue in the future: If you're using github actions to generate your daux page, this entry in the config.json should fix it

```
{
"templates": "daux/templates",
}
```
