### ISSUE TITLE
main.min.css missing for single-page HTML output

### ISSUE THREAD

**Issue by gwittenburg** [dauxio/daux.io#294] opened 2022-01-31 00:07 UTC
**Describe the bug**
When generating single-page HTML output, the output seems to lack styling. Shell output includes a warning that main.min.css is missing. Maybe a packaging issue (using daux/daux.io:latest, image ID 0c0c294fdfe0)?

`Warning: file_get_contents(themes/daux_singlepage/css/main.min.css): Failed to open stream: No such file or directory in /daux/libs/Format/HTMLFile/Book.php on line 21`

**To Reproduce**
Run the following command with the currently latest (v0.18.0) Docker image:
`docker run -it -w /build -v "$PWD":/build --rm daux/daux.io daux generate --format=html-file`

**Expected behavior**
Above command completes without warning regarding missing CSS file. Styles are applied to output (if any).

**Screenshots**
n/a

**Desktop (please complete the following information):**
Ubuntu 21.10

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by onigoetz** [comment] 2022-01-31 10:11
Hi, that's curious the file should be present, I'll investigate that.

**Comment by onigoetz** [comment] 2022-01-31 21:42
Should be fixed by https://github.com/dauxio/daux.io/commit/4e499531dd4449dbd28319d16198e15a3bd1da29 
Released in [version 0.18.1](https://github.com/dauxio/daux.io/releases/tag/0.18.1)

**Comment by gwittenburg** [comment] 2022-02-01 07:55
Thanks so much, Stéphane!

After upgrading to 0.18.1, I now get this warning for single-page HTML output (multi-page is fine):
`Warning: file_get_contents(/daux/themes/../style.css): Failed to open stream: No such file or directory in /daux/libs/Format/HTMLFile/Book.php on line 23`

If it's helpful, the directory layout is like this, and I'm also including the config.json below:

```
georg@Georgs-XPS15:~/Inspirient/Development/website$ find docs/
docs/
docs/_index.md
docs/en
docs/en/00_Welcome.md
docs/en/20_Introduction_to_Autonomous_Analytics.md
docs/en/50_Use_Cases
docs/en/50_Use_Cases/10_Polling_and_Survey_Analytics.md
docs/en/30_Working_with_Inspirient.md
docs/en/80_Further_Reading.md
docs/en/40_Best_Practices
docs/en/40_Best_Practices/10_Data_Priorities_and_Annotations.md
docs/en/40_Best_Practices/20_Using_Tags_to_Navigate_Results.md
docs/en/40_Best_Practices/30_Collaboratively_Prioritising_Insights.md
docs/en/60_Technical_Deep-dives
docs/en/60_Technical_Deep-dives/10_Scoring_Methods.md
docs/en/70_Frequently_Asked_Questions.md
docs/en/10_Quick_Overview.md
docs/images
docs/images/webapp_guidance_table_selection.png
docs/images/webapp_recent_analysis.png
docs/images/autonomous_analytics_transforms_datasets_into_results.png
docs/images/webapp_download_center.png
docs/images/webapp_guidance_dimension_priorities.png
docs/images/inspirient_webapp_on_ipad.png
docs/images/webapp_detail_view.png
docs/images/webapp_user_interface.png
docs/images/webapp_guidance_dimension_context.png
docs/images/inspirient_automated_analytics_engine_architecture.png
docs/images/webapp_four_view_modes.png
docs/images/webapp_file_submission.png
docs/images/webapp_search_field_with_tags.png
docs/config.json
docs/style.css
docs/de
docs/de/00_Willkommen.md
```

**config.json**
```
{
	"title": "Inspirient",
	"author": "Inspirient GmbH",
	"tagline": "User Guide and Documentation",
	"image": "../images/logos/Inspirient.png",
	"languages": { "en": "English", "de": "German" },
	"language": "en",
	"html": {
		"links": {
			"Main Website": "https://www.inspirient.com/",
			"Contact / Support": "https://www.inspirient.com/contact.php"
		},
		"twitter": ["inspirient"],
		"search": true
	}
}
```

**Comment by onigoetz** [comment] 2022-02-01 08:02
That's curious, do you have a custom theme directory ?
I'll have a look at it tonight

**Comment by gwittenburg** [comment] 2022-02-01 09:56
I don't think I have a custom theme directory (i.e., nothing in the directory listing above, which I believe to be complete).

From afar it looks a bit like an issue with my style.css being on level above the directories with the *.md files. Maybe construction of the path "/daux/themes/../style.css" needs to take this into account because "../style.css" would be correct in most of the generated output, but in this case contracts to "/daux/style.css".

**Comment by onigoetz** [comment] 2022-02-05 20:03
Hi, Covid got to me before I could get to this :P, feeling much better now :)

I've had a look and can't reproduce the error you have.

```
❯ docker run --rm -it -w /build -v "$PWD":/build daux/daux.io:0.18.1 \
    daux generate --format=html-file
Cleaning destination folder ...                                           [  OK  ]
Generating DAUX.IO                                                        [  OK  ]
Generating Getting Started                                                [  OK  ]
Generating Auto Syntax Highlight                                          [  OK  ]
Generating CommonMark compliant                                           [  OK  ]
Generating Edit on GitHub links                                           [  OK  ]
Generating Front Matter                                                   [  OK  ]
Generating Internal links                                                 [  OK  ]
Generating Landing page                                                   [  OK  ]
Generating Live mode                                                      [  OK  ]
Generating Math, Diagrams and Flowcharts                                  [  OK  ]
Generating Multilanguage                                                  [  OK  ]
Generating Multiple Output Formats                                        [  OK  ]
Generating Navigation and Sorting                                         [  OK  ]
Generating Search                                                         [  OK  ]
Generating Static Site Generation                                         [  OK  ]
Generating Table of contents                                              [  OK  ]
Generating Examples                                                       [  OK  ]
Generating Code Highlighting                                              [  OK  ]
Generating Hello World                                                    [  OK  ]
Generating Hallo Welt                                                     [  OK  ]
Generating привет мир                                                     [  OK  ]
Generating 你好世界                                                           [  OK  ]
Generating Configuration                                                  [  OK  ]
Generating Confluence upload                                              [  OK  ]
Generating Html export                                                    [  OK  ]
Generating Creating a Processor                                           [  OK  ]
Generating Creating a Theme                                               [  OK  ]
```

**Comment by onigoetz** [comment] 2022-12-10 13:18
Can't reproduce the issue

**Closed by onigoetz** 2022-12-10 13:18 UTC
Labels: bug
