### ISSUE TITLE
html.edit_on returns incorrect links

### ISSUE THREAD

**Issue by leominov** [dauxio/daux.io#219] opened 2020-08-09 06:18 UTC
**Describe the bug**

Configured `html.edit_on` or `html.edit_on_github` options returns incorrect links in UI.

**To Reproduce**

1. Extract [Archive.zip](https://github.com/dauxio/daux.io/files/5046807/Archive.zip) (configuration file included)
2. Run `docker run --rm -it -v $(PWD):/docs -w /docs -p 8085:8085 daux/daux.io:0.14.0 /bin/bash -c 'daux serve -c config.json --source ./ --host 0.0.0.0'`
3. Navigate to `http://127.0.0.1:8085/en/index`
4. `Edit on GitLab` contains wrong link - https://gitlab.com/yuccastream/sites/docs/-/tree/master/n/00_index.md

**Expected behavior**

`Edit on GitLab` with https://gitlab.com/yuccastream/sites/docs/-/tree/master/en/00_index.md link.

**Comment by onigoetz** [comment] 2020-08-14 20:11
Hi,
thanks for the report, I was able to reproduce this issue and I'm not exactly sure what's the issue yet, but I also have found a fix for you

by running 
1) move all your documentation files to a `docs` folder (but don't `cd` into it)
2) run `docker run --rm -it -v $(PWD):/docs -w /docs -p 8085:8085 daux/daux.io:0.14.0 daux serve --host 0.0.0.0`
  - removes the `--source ./` as `$(PWD)/docs` is the default folder
  - removes the `-c config.json` as `$(PWD)/docs/config.json` is the default configuration lookup path
  - removes `/bin/bash -c` since we don't need an interactive bash session`

This should work for you, however I will still check why the urls are incorrect in the first place.

**Comment by onigoetz** [comment] 2020-08-14 20:35
So I found the issue, it was an incorrectly cleaned path to the directory, it's fixed in master, I will release it in the next few days

**Closed** 2020-08-14 20:40 UTC

**Comment by leominov** [comment] 2020-08-15 04:25
Thanks
