### ISSUE TITLE
live mode: svg not displayed, static PDF files not served

### ISSUE THREAD

**Issue by MaitreDede** [dauxio/daux.io#281] opened 2021-11-29 21:51 UTC
Hello :slightly_smiling_face: 

**Describe the bug**
- I am editing the pages with VSCode, I have an extension that integrates drawio, and can edit `.drawio.svg` files. I add them to markdown as classical image. image placeholder is displayed, but not svg content. Also, if I open image in new tab, browser downloads it (chrome and firefox)
- I have added static PDF files : link is displayed "red", and clicking on it gives error page

**To Reproduce**
1. Using docker daux/daux.io:0.16.2
2. Commandline: docker run --rm -it --publish 8085:8085 -v ${PWD}:/daux/docs:ro daux/daux.io:0.16.2 daux serve
3. Page containing SVG as image : `![alt](my.drawio.svg "wonderful image")`
4. With link to pdf in same file `[my pdf](my.pdf)`

**Expected behavior**
- image displayed
- pdf downloaded

**Desktop (please complete the following information):**
 - OS: Debian bullseye
 - Browser google chrome 97.0.4692.20 (beta), firefox 78.15.0esr

**Comment by onigoetz** [comment] 2021-12-01 22:00
I cannot reproduce the issue with the svg file (And use daux with svgs daily). I'm not exactly sure how to investigate this for now, I'll have a further look tomorrow.

However I can reproduce the red pdf link issue, I will look into that and how to fix it.

**Comment by onigoetz** [comment] 2021-12-02 19:05
Hmm, actually I made a typo in the PDF url, after fixing it it worked.

can you try maybe to use relative paths ? 

```
![alt](./my.drawio.svg "wonderful image")
[my pdf](./my.pdf)
```

**Comment by onigoetz** [comment] 2021-12-18 19:49
I'm closing this issue as I couldn't reproduce the bug and have no news.
Feel free to reopen if you find a new issue related to this.

**Closed by onigoetz** 2021-12-18 19:49 UTC
Labels: support
