### ISSUE TITLE
Not properly linked when index.md is not being used

### ISSUE THREAD

**Issue by seigieu** [dauxio/daux.io#50] opened 2018-05-15 06:37 UTC
I recently updated Daux and my can't properly generate docs.

	docs
	- 01_test1 (links to index.md)
	-- index.md (works fine)
	- 02_test2 (links to href="#" and does nothing)
	-- 01)faq.md (cannot be accesse)

# Edit
Just realized its a JS Error related
ReferenceError: jQuery is not defined[Więcej informacji]
tipuesearch.js:365:1
ReferenceError: $ is not defined[Więcej informacji]
index.html:11

**Comment by seigieu** [comment] 2018-05-15 06:41
Downgraded to `0.7.1` and works fine.

**Comment by seigieu** [comment] 2018-05-15 06:44
as a side note: in 0.7.2 show hide code checkbox is being always shown, or rather its not being hidden when there is no code blocks

**Comment by onigoetz** [comment] 2018-05-15 07:03
Hello, I'll have a look about the jQuery issue, you can access the faq page in 0.7.1 ?
Is it a typo in the description or is the file really named `01)faq.md` ?

**Comment by seigieu** [comment] 2018-05-15 09:13
It's a typo. it should be `01_faq.md`
0.7.1 jQuery works fine. The poroblem is dynamic sliding of menu does not work and thus FAQ cannot be accessed since parent elemen toggle does not work.

**Comment by onigoetz** [comment] 2018-06-05 19:47
Hello, do you still have the issue in 0.7.3 ? I can't reproduce your error

**Comment by seigieu** [comment] 2018-06-14 11:08
0.7.3 and 0.7.4 with php 7.2.6 (as i had to upgrade for Daux to work...) does not work. Still jQuery is not defined for me.

**Comment by seigieu** [comment] 2018-06-14 11:10
May be related to new bug I submitted #57

**Comment by onigoetz** [comment] 2018-09-21 14:31
closing, As discussed in #57

**Closed by onigoetz** 2018-09-21 14:31 UTC
Labels: bug
