### ISSUE TITLE
Heading (h1) tags not generating correctly

### ISSUE THREAD

**Issue by MatthewJamesHanson** [dauxio/daux.io#278] opened 2021-11-17 04:47 UTC
I'm not sure what caused this. We've been using daux without this issue. Now the < h# > tags are not being generated correctly on the site on any page anywhere. 

In each case, the symptoms are like this:
![image](https://user-images.githubusercontent.com/25975905/142135920-a495480d-b28a-49ea-9629-d3ebac2f4390.png)

while the markdown is like this:
![image](https://user-images.githubusercontent.com/25975905/142136027-5fb65391-f807-4e71-b722-fab7b2dfc07f.png)

and the html is like this;
![image](https://user-images.githubusercontent.com/25975905/142136064-b8dad697-fa3a-49ce-a00f-157016b81361.png)

Thanks for any help

-- Edit

I can put this into the markdown and it works as expected

`<h2> some heading</h2>`

For any one else, if you are having this problem. This is a nice solution (until the issue is fixed). This allows for the table of contents to still be created (whereas if you just use the manual `<h#>` tags, the table of contents is not generated with content.
![image](https://user-images.githubusercontent.com/25975905/142349955-2d7e9d83-1f29-4a3e-8edc-f2386e852b92.png)

**Comment by onigoetz** [comment] 2021-12-01 21:36
Hello, sorry for the delay.

I can't reproduce your issue just out of the box so I'd need to have a bit more information on your setup

- what version of Daux are you using ?
- are you using it through a Docker image or installed through Composer ?
- if composer, is it in a project with other dependencies (like commonmark)
- are you using any Processor ?

**Comment by MatthewJamesHanson** [comment] 2021-12-06 07:31
what version of Daux are you using ?
**daux/daux.io 0.16.2**

are you using it through a Docker image or installed through Composer ?
**Installed through composer.**

if composer, is it in a project with other dependencies (like commonmark)
**Never heard of commonmark. No dependencies that I'm aware of. We just use a directory of markdown files -- so our setup is basic.**

are you using any Processor ?
**I didn't configure any specifically, so only any that are in use by default.**

**Comment by MatthewJamesHanson** [comment] 2022-04-13 08:09
I resolved this manually. The issue is still odd and not resolved, but for others (if any) here is what I did:
Upgraded PHP to 8.1.4, then had to resolve this bug (https://github.com/barryvdh/laravel-dompdf/issues/757) manually, by changing line 79 in `C:\Users\<me>\AppData\Roaming\Composer\vendor\daux\daux.io\libs\Tree\Directory.php`
`                $buckets['numeric'][abs(($exploded[0])][$key] = $entry;`
to this line
`                $buckets['numeric'][abs((int)$exploded[0])][$key] = $entry;`

ciao!

**Comment by onigoetz** [comment] 2022-12-10 13:27
Thanks for the feedback, I added the proposed fix

**Comment by onigoetz** [comment] 2022-12-10 14:09
This change has been released in [0.20.1](https://github.com/dauxio/daux.io/releases/tag/0.20.1)

**Closed by onigoetz** 2022-12-10 14:09 UTC
Labels: Waiting for release
