### ISSUE TITLE
Dont change <br /> in source MD file to <br> in generated HTML. It breaks confluence upload.

### ISSUE THREAD

**Issue by KoenDG** [dauxio/daux.io#264] opened 2021-06-14 16:06 UTC
**Describe the bug**
Confluence upload expects an XML document, in which all tags must be closed. `<br>` breaks that.
XML accepts `<br />`, which fixes this, but I've no way to set this, as all generation happens inside the container and uploads everything straight away.

**To Reproduce**
Generate an MD file with `<br />` at some point in the file.

Performing a command like `daux generate -s . --format confluence` or even HTML format, will change the `<br />` to `<br>`.

**Expected behavior**
No change performed on tags like this. Same with `<hr>`, `<img>` and `<input>`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser N/A
 - Version: Daux 0.16.2

**Comment by onigoetz** [comment] 2021-06-15 20:00
Hello,

I've made a quick test and can't reproduce the issue you're describing:

```
<?php namespace Todaymade\Daux\ContentTypes\Markdown;

use PHPUnit\Framework\TestCase;
use Todaymade\Daux\Config;

class RendererTest extends TestCase
{
    public function testLineBreak()
    {
        $converter = new CommonMarkConverter(["daux" => new Config()]);

        $input = "Something Something\nSomething\n\n<br />\n\nSomething";
        $output = "<p>Something Something\nSomething</p>\n<br />\n<p>Something</p>";

        $this->assertEquals($output, trim($converter->convertToHtml($input)));
    }
}

```

Do you have a project or a small repro case where I can experiment this ?

**Comment by KoenDG** [comment] 2021-06-17 08:09
[test.md](https://github.com/dauxio/daux.io/files/6668488/test.md)

I've attached a small `.md` file which reproduces it locally. Both with latest and older versions down to 0.15.1

**Comment by onigoetz** [comment] 2021-07-18 20:47
Hello, I'm sorry for the delay.

I checked the file you sent and its content has

```
***Status Code:*** 900

<br>

```

Your statement mentioned

> Performing a command like `daux generate -s . --format confluence` or even HTML format, will change the `<br />` to `<br>`.

However in this example, you already have `<br>` to begin with.
Daux and more precisely the markdown parser it uses don't touch things that are already HTML.

Do you have an example that doesn't start with `<br>` but has `<br>` after generation ?

**Comment by KoenDG** [comment] 2021-07-22 11:42
Apologies, I'm currently working on other things and it's been too long to remember the exact steps I used to conclude this.

Can you try processing the file again, but change `<br>` to `<br />` before you do so? Does that change anything?

**Comment by onigoetz** [comment] 2021-07-23 18:59
If the input already contains `<br />` it will be left as-is. so will upload correctly.

I have to say that a few days ago I had the case you mention but tracking down my own content I discovered that one of my markdown files contained `<br>` directly in the content. Changing it to `<br />` fixed the upload.

I'm closing this issue for now. Feel free to reopen it if you have a reproducible case.

**Closed by onigoetz** 2021-07-23 18:59 UTC
