### ISSUE TITLE
Front Matter Title don't work in _index.md

### ISSUE THREAD

**Issue by gerundt** [dauxio/daux.io#29] opened 2017-11-24 12:13 UTC
I create today a `_index.md` file and use Front Matter Title in this file but it seems to be ignored.

In the page title and the menu he use the file name.

**Comment by onigoetz** [comment] 2017-12-11 13:27
Hello, yes currently it's not taken in account. I'll have a look to have it supported.

**Comment by onigoetz** [comment] 2017-12-11 13:29
Closed as duplicate of #27

**Closed** 2018-06-05 19:49 UTC
Labels: enhancement
